Added auto manager detection and set it as default manager, added bun manager support (#20)
* purge .DS_Store and prepare-release-better

* update prepare-release-action for auto CHANGELOG headers

* updated docs and defaults

* add support for auto manager detection and bun as an option

* what condition my condition is in

* add better feedback on autodetection

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -27,7 +27,7 @@ inputs:
   manager:
     description: "The package manager to use."
     required: false
-    default: npm
+    default: auto
   package:
     description: "The name of the package."
     required: false
@@ -83,13 +83,6 @@ runs:
         if [ "${{ inputs.slug }}" == "" ]; then
           echo "::error title=Slug is not set!::You must specify a GitHub repo slug in order to run this shit."
           exit 47
-        fi
-        echo "::endgroup::"
-
-        echo "::group::Ensure ${{ inputs.manager }} is installed"
-        if ! command -v ${{ inputs.manager }} &> /dev/null; then
-          echo "::error title=Package manager does not exist!::You must ensure the underlying package manager ${{ inputs.manager }} is installed."
-          exit 48
         fi
         echo "::endgroup::"
 
@@ -185,12 +178,47 @@ runs:
           for DIR in "${DIRS[@]}"; do
             PKGDIR="${{ github.workspace }}/auto-deploy-action-tmp/$DIR"
             cd "$PKGDIR"
-            echo "Updating $PKGDIR/package.json with ${{ inputs.manager }} to ${{ steps.auto-deploy-action.outputs.package }}${{ steps.auto-deploy-action.outputs.separator }}${{ steps.auto-deploy-action.outputs.version }} with ${{ inputs.args }}"
-            if [ "${{ inputs.manager }}" == "yarn" ]; then
-              yarn add ${{ steps.auto-deploy-action.outputs.package }}${{ steps.auto-deploy-action.outputs.separator }}${{ steps.auto-deploy-action.outputs.version }} ${{ inputs.args }}
-            elif [ "${{ inputs.manager }}" == "npm" ]; then
-              npm install ${{ steps.auto-deploy-action.outputs.package }}${{ steps.auto-deploy-action.outputs.separator }}${{ steps.auto-deploy-action.outputs.version }} ${{ inputs.args }}
+
+            # auto detect manager
+            if [ "${{ inputs.manager }}" == "auto" ]; then
+              echo "::group::Detecting package manager"
+              if [[ -f "bun.lock" ]]; then
+                PKGMGR="bun"
+                echo "Found bun.lock, using $PKGMGR"
+              elif [[ -f "bunb.lock" ]]; then
+                PKGMGR="bun"
+                echo "Found bunb.lock, using $PKGMGR"
+              elif [[ -f "package-lock.json" ]]; then
+                PKGMGR="npm"
+                echo "Found package-lock.json, using $PKGMGR"
+              elif [[ -f "yarn.lock" ]]; then
+                PKGMGR="yarn"
+                echo "Found yarn.lock, using $PKGMGR"
+              else
+                PKGMGR="npm"
+                echo "Could not find any lockfiles, using $PKGMGR"
+              fi
+              echo "::endgroup::"
+            else
+              PKGMGR="${{ inputs.manager }}"
             fi
+
+            echo "::group::Ensuring $PKGMGR is installed"
+            if ! command -v "$PKGMGR" &> /dev/null; then
+              echo "::error title=Package manager does not exist!::You must ensure the underlying package manager $PKGMGR is installed."
+              exit 48
+            fi
+            echo "::endgroup::"
+
+            echo "Updating $PKGDIR/package.json with $PKGMGR to ${{ steps.auto-deploy-action.outputs.package }}${{ steps.auto-deploy-action.outputs.separator }}${{ steps.auto-deploy-action.outputs.version }} with ${{ inputs.args }}"
+            if [ "$PKGMGR" == "bun" ]; then
+              bun add ${{ steps.auto-deploy-action.outputs.package }}${{ steps.auto-deploy-action.outputs.separator }}${{ steps.auto-deploy-action.outputs.version }} ${{ inputs.args }}
+            elif [ "$PKGMGR" == "npm" ]; then
+              npm install ${{ steps.auto-deploy-action.outputs.package }}${{ steps.auto-deploy-action.outputs.separator }}${{ steps.auto-deploy-action.outputs.version }} ${{ inputs.args }}
+            elif [ "$PKGMGR" == "yarn" ]; then
+              yarn add ${{ steps.auto-deploy-action.outputs.package }}${{ steps.auto-deploy-action.outputs.separator }}${{ steps.auto-deploy-action.outputs.version }} ${{ inputs.args }}
+            fi
+
             cd "${{ github.workspace }}/auto-deploy-action-tmp"
           done
         echo "::endgroup::"
